config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  
  get '/home', to: 'pages#home'

  resources :recipes do
    member do
      post 'like'
    end
  end
  
  resources :chefs, except: [:new, :destroy]
  
  get '/register', to: 'chefs#new'
  
  get '/login', to: "logins#new"
  post '/login', to: "logins#create"
  get '/logout', to: "logins#destroy"
  
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]
  

end

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to MyRecipes App</h1>
  
  <h2>
    This is the home page for the Professional Ruby on Rails Developer Course on Udemy
  </h2>
  
  <%= link_to "Sign up now!", register_path, class: "btn btn-lg btn-success" %>
</div>
<div class="row">
  <div class="col-lg-4">
    <h3 class="midrow">
      View Recipes as Guest User
    </h3>
    <h2 class="left">Browse and view recipes as a guest and Sign up later</h2>
    <p><%= link_to "Browse Recipe Listings", recipes_path, class: "btn btn-warning btn-small" %></p>
  </div>
  <div class="col-lg-4">
    <h3 class="midrow">
      Sign in to your account
    </h3>
    <h2 class="left">Add/update your recipes/create reviews/like-dislike recipes and much much more!</h2>
    <p><%= link_to "Log in to your account", login_path, class: "btn btn-warning btn-small" %></p>
  </div>
  <div class="col-lg-4">
    <h3 class="midrow">
      View Recipes as Guest User
    </h3>
    <h2 class="left">Browse and view recipes as a guest and Sign up later</h2>
    <p><%= link_to "Browse Recipe Listings", "", class: "btn btn-warning btn-small" %></p>
  </div>
</div>